### PR TITLE
Add a filter function for raw data

### PR DESCRIPTION
**Pull request by surygeng**
Add a butterworth filter function for getting LFP from raw data.

### CODE REVIEW

**Review by pupster90 — APPROVED** [review]
Looks good, this has the filter function in it

**Comment by pupster90** [comment]
does this merge?

**Comment by atspaeth** [comment]
What's the difference between this and the one that's just called `filter()`? (Added by @ashsrobbins a while back.) Can we get rid of one of the two?

**Comment by surygeng** [comment]
This new function is simpler. It can be lowpass, highpass, or bandpass, depending on the cutoff value. It returns the same shape of data as the input. Also, the scipy sosfiltfilt function is used since it performs well over other filters. Frequency response was checked.

**Comment by atspaeth** [comment]
Great, so the only pro of the old one is that it's chunked/incremental. @ashsrobbins do we actually use that? Is it faster in practice on sufficiently large data or something?

Otherwise I can put together a PR that deprecates the old one and uses the new one in `SpikeData.from_thresholded()`

**Pull request merged**
