### PR TITLE
Added concatenate method, fixed fatal error in subset(), and fixed issue with neuron_attributes being empty when reading from phys data

### PR DESCRIPTION
**Pull request by MissValeska**

### CODE REVIEW

**Comment by atspaeth** [comment]
Wow, a PR with code review? Thanks for being the first person to treat this like a software project ;)

But the bugfix in `SpikeData.subset()` looks wrong to me. I'm not very familiar with `neuron_attributes` (I think @ashsrobbins added it but since the point of the method is to select only a subset of neurons, the condition in this block
```python
        neuron_attributes = []
        if len(self.neuron_attributes) == len(units):
            neuron_attributes = [self.neuron_attributes[i] for i in units]
```
should virtually never be satisfied, and you'll always lose the attributes on subsetting. It should logically work more like the line for `neuron_data` (which Ash deprecated in favor of `neuron_attributes`), maybe:
```python
neuron_attributes = [attr for i,attr in enumerate(self.neuron_attributes) if cond(i)]
```

**Comment by atspaeth** [comment]
`concatenate_spike_data()` is a good operation to have! I just needed this recently actually. But can we just value error if the lengths don't match? There's no sensible default for combining them in that case.

Also the current implementation doesn't handle `neuron_attributes` and will silently break `metadata` if you combine two objects that have overlapping keys. I think we're about to get rid of `neuron_data` because it never had any users, but I'd like to see a warning or something if metadata values are being overridden.

**Comment by MissValeska** [comment]
> 

You're welcome! Just doing my part! :)
Actually, I fixed neuron_attributes in this PR, so it is populated correctly, at least for the read_phys method. This is based off of my use cases in the Math of the Mind class I just completed. Considering that neuron_attributes was previously not populated, this caused a fatal error without the condition. The condition protects against a fatal error in the case that neuron_attributes is empty. 

You won't lose attributes because you will retain the original SpikeData object on your end, it's just that the new object won't have attributes for which it does not have data, which is exactly how it should work in my opinion. An object shouldn't have attributes for which it does not have data based off of a memory of where it came from.

**Comment by MissValeska** [comment]
> `concatenate_spike_data()` is a good operation to have! I just needed this recently actually. But can we just value error if the lengths don't match? There's no sensible default for combining them in that case.
> 
> Also the current implementation doesn't handle `neuron_attributes` and will silently break `metadata` if you combine two objects that have overlapping keys. I think we're about to get rid of `neuron_data` because it never had any users, but I'd like to see a warning or something if metadata values are being overridden.

In my use case in the class, I needed to add neurons together from different SpikeData objects taken from before and after stimulation. Considering that the before and after stimulation datasets were of different lengths in terms of recording time, I needed to standardize them to a common length by the lowest common denominator. As such, I figured it would be important for this to be done automatically, but I suppose it's up to interpretation if that should be done by the user in order to warn them. However, assuming they've read the documentation/comments that will come with the library, they would know how it handles that and presumably write their code accordingly. In my use case, this was valuable and I felt it would be useful to just include it within the method. Let me know if you have any other thoughts or a different opinion! :)

Good point about the overlapping keys; I still need to consider how to resolve that actually! I should have done so before submitting the PR; mea culpa! neuron_attributes should work, however now that I have it actually being populated, which wasn't the case before when reading from phys files. It is probably now safe to actually deprecate it, once I ensure it isn't being used elsewhere in the code base. Though, it may break existing code that relies on it outside of the library. I, for example, used it in my class, but that can be replaced with neuron_attributes now that I've made it not be empty.

**Comment by atspaeth** [comment]
> Actually, I fixed neuron_attributes in this PR, so it is populated correctly, at least for the read_phys method.
Wait, read_phy_files didn't populate it to begin with? Now I'm wondering where `neuron_attributes` was ever used in the first place... @ashsrobbins , @surygeng ?
> The condition protects against a fatal error in the case that neuron_attributes is empty.
Oh, I didn't know about this issue! I created `neuron_data` with the invariant that it would have an entry for each neuron in any field that was present so I thought it would be like that here too. I guess since `neuron_attributes` is a list of structs that's not really possible, so we definitely need to handle a case with empty attributes.

So now I see the rationale for what you're doing, but I don't think I explained my complaint very well. When I said "lose attributes" I meant that attributes for a particular neuron aren't getting propagated to the new subsetted SpikeData even if it contains that neuron's spike train. With the condition on `len`, this code won't propagate any attributes at all unless the number of units selected for the new subset is the same as the number of units in the original SpikeData, in which case it correctly propagates all of them. So this method works if you're using `subset()` to permute the units, but it should also be possible for `units` to be a small subset of the indices in the original object, returning a new object whose attributes are a corresponding subset of the original attributes.

PS I think my suggested code actually would handle the corner case with empty attributes even though I didn't mean to :)

**Pull request merged**
